### ISSUE TITLE
The corner goes black when the window is next to edge of screen

### ISSUE THREAD

**Issue by Hibanaw** [a-parhom/LightlyShaders#15]
Also happens when the window is maximized.
Maybe it's of no need to render the shadow anymore in the case.
![image](https://user-images.githubusercontent.com/61813396/149959735-7e079396-0f54-48d1-92ce-19134157b929.png)

**Comment by a-parhom** [comment]
I'm aware of this issue, just haven't figured out how to fix that yet. I think I'll have some time on weekend to return to this.

**Comment by semarainc** [comment]
i think its not just on the edge of the screen , but this also affected when window is touching panel
(its not black though but the rounded effect on shadow seems fail when the window is touching panel in plasma)
i'm using oxygen as window decoration (affected with border and no border window)

![image](https://user-images.githubusercontent.com/19622207/150682500-b6953901-bea3-445d-9792-d382747bb8d8.png)


hope this can help you ^^
sry if there is something inconvenience

**Comment by jsebean** [comment]
Just to add, the corner issue happens when windows are *directly* in line with another window.When you're off by just one pixel, it doesn't happen.
![image](https://user-images.githubusercontent.com/640219/150693424-4d151df4-a227-48fc-a0f3-6f8019aacd58.png)
![image](https://user-images.githubusercontent.com/640219/150693437-111c6c27-bd47-4110-bb35-747c3ebb6edd.png)

**Comment by jsebean** [comment]
Actually, I've noticed this works on anything with very well defined lines when you move a window up to it.

**Comment by a-parhom** [comment]
The branch 'precache_shadows' includes the fix for this issue. Now the effect does one offscreen render of the window, caches the shadows and then reuses them. This may have a performance impact when the shadows need to be update though. I'm not sure if the current solution of validating the need for shadows cache update is the best one, so not merging to master right now.

**Comment by a-parhom** [comment]
Actually, I think the additional offscreen render can be done only for windows, that are next to the edges of the screen. This should improve the performance. I'll try to add that in couple of days.

**Comment by a-parhom** [comment]
Done in commit b84282b949c7ab8279c22d9fd1c305e0cfcf64bd.

**Comment by a-parhom** [comment]
Fixed some artifacts in commit 8d24395a1f2ff531f28fae93b81d5790d1224bd5. Looks ok now. I'll test this for some time and merge to master.

**Comment by a-parhom** [comment]
Fixed horizontal flipping of shadows and merged to master.
