### ISSUE TITLE
No rounded corners for no-border windows

### ISSUE THREAD

**Issue by Hibanaw** [a-parhom/LightlyShaders#16]
![image](https://user-images.githubusercontent.com/61813396/150138382-d9c3de63-d1ee-457d-9f3e-0387cc27e53a.png)
Happens to qt, electron and Wine apps that don't use a system border.
Very common in Chinese made linux apps.
Hope this can be fix.
Thanks!

**Comment by Hibanaw** [comment]
Btw, here's a kwin plugin for cutefishos(a desktop environment)
https://github.com/cutefishos/kwin-plugins/tree/main/plugins/roundedwindow
It works well in cutefishos.
Hope it can help you

**Comment by a-parhom** [comment]
The plugin intentionally ignores windows, that have no shadow. And those on the screenshot, as I can see, don't have it. That's done to skip rounding full-screen videos etc. I don't think it would be easy to distinguish those windows from anything else, that is not meant to be rounded. And if those apps are not meant to use system theming or shadows at all, maybe there is no much point in rounding them as well.

As far as I know, CutefishOS uses a fork of KWin, that does not have "korners" bug at all. And because of that their latest implementation of ShapeCorners is very different from this one or the original.

**Comment by Hibanaw** [comment]
> The plugin intentionally ignores windows, that have no shadow. And those on the screenshot, as I can see, don't have it. That's done to skip rounding full-screen videos etc. I don't think it would be easy to distinguish those windows from anything else, that is not meant to be rounded. And if those apps are not meant to use system theming or shadows at all, maybe there is no much point in rounding them as well.

Would you like to make a whitelist filter for users to force enable the effect for specific windows? This can help users like me a lot.

> As far as I know, CutefishOS uses a fork of KWin, that does not have "korners" bug at all. And because of that their latest implementation of ShapeCorners is very different from this one or the original.

Oh,, that's a bad news.

**Comment by a-parhom** [comment]
I think a white list could be done. Maybe not as first priority, though.

**Comment by Hibanaw** [comment]
Here's another problem,
for it doesn't add rounded corners for no-border/no-shadow windows, it doesn't work well with the kwin script "Hide titles", which automatically hide the window border of maximized windows. 
I have a suggestion:
how about disable the effect only when the window's size equals to the monitor size? This might be a solution?

**Comment by a-parhom** [comment]
Please, try the latest changes.

**Comment by Hibanaw** [comment]
> Please, try the latest changes.

Works pretty well! Thanks a lot!
