### ISSUE TITLE
Glitch on corners when window appears/disappears

### ISSUE THREAD

**Issue by astudentinearth** [a-parhom/LightlyShaders#57]
https://user-images.githubusercontent.com/95227070/184146801-09db0b3c-d11b-49b9-8c92-c0b2bfb49f27.mp4

When a window (Konsole in this case) appears, weird glitches appear on the corners. I tested this with Breeze window decoration. I'm on commit 04432c4a704d561541ae2be1f9907bb7bb783a2b, which is the latest commit at the time of writing. Commit 664a3fb6535cdcfdbca1a65312d70e6016a9c55f does have the same issue as well. Scale animation is used when a window appears/disappears. This is a similar effect to the korner bug, except the glitched corners appear somewhere far from the window, and move towards the window corners as animation progresses, where they eventually disappear.
Note: I'm using X11 and haven't tested this on Wayland.
```
My LightlyShaders configuration is as follows:
Radius: 10px
Shadow offset: 2px
No outline around window
Disabled for maximized windows
Rounded corners
```
```
My system information is as follows:
Arch Linux with linux-5.18.16-arch-1-1
Plasma 5.25.4
KDE Frameworks 5.96.0
Qt 5.15.5
GPU: Nvidia Geforce GTX 1060 6GB (using the proprietary drivers, version 515.65.01-2)
```
```
My compositor settings is as follows:
Scale method: Accurate
Latency: Balance
Vsync: Automatic
Thumbnails are kept only for shown windows
```

**Comment by a-parhom** [comment]
Unfortunately, this effect is not compatible with this kind of window animation. You can try fade-in, fade-out animations, the plugin plays well with them on Plasma 5.25.

I'll close this issue for now, because it can't be fixed with current approach of rendering rounded corners. I'm working on total refactoring, which hopefully can make the plugin compatible with all the standard animations, though KWin API seems to be little limited, so no estimates or even chances that it will happen.
